export const profile = {
  name: "Matin Khajehfard",
  location: "Hoofddorp, Netherlands",
  roles: ["Software Engineer", "Fullstack Developer", "AI/Automation Engineer"],
  valueProposition:
    "I build reliable full stack and automation systems: Vue/TypeScript frontends, Node/Java APIs, SQL data models, and delivery backed by traceability and clear evidence.",
  email: "kh.matin21@gmail.com",
  links: {
    linkedin: "https://www.linkedin.com/in/matin-khajehfard",
    github: "https://github.com/Bloody-BadAim",
  },
  preferences: [
    "Part-time",
    "Hybrid",
    "Early-stage teams",
    "Open to freelance",
    "Open to 2027 internship",
  ],
  differentiators: [
    "Fluor: Delivered event-driven audit trail and searchable Web UI reporting in STIBO STEP for PDM pipelines. Evidence available on request.",
    "EKB-AI: Built PDF to FAISS semantic search with page-level traceability and NL↔EN processing. Public repo available.",
    "AI Marathon 2025–2026: Program lead across 7 labs, 9 events, and 9 study associations. Schedules and materials available.",
    "Engineering style: Structured logging, debuggability, and repeatable workflows for reliable delivery.",
  ],
  skills: {
    frontend: ["Vue.js", "TypeScript", "JavaScript", "HTML/CSS", "Vite"],
    backend: [
      "Node.js",
      "Express",
      "NestJS",
      "Java (Spring Boot)",
      "REST APIs",
      "PostgreSQL",
      "MySQL",
      "Prisma",
      "JWT",
      "OAuth",
      "Sessions",
    ],
    ai: [
      "Python",
      "FAISS",
      "HuggingFace embeddings",
      "LangChain",
      "Chunking and overlap",
      "Metadata traceability",
      "pdfplumber",
      "pandas",
      "Argos Translate",
      "PyTorch",
    ],
    automation: ["n8n", "Power Automate", "Zapier", "Webhooks", "Validation and retries"],
    testing: ["Cypress", "Vitest", "Git", "ESLint", "Render (deployment)"],
  },
  leadership: {
    title: "AI Marathon (HvA Applied AI) — Program Lead",
    details:
      "Own program operations and stakeholder coordination for an AI event series connecting labs and study associations (7 labs, 9 events, 9 associations).",
  },
  experience: [
    "Fluor (Sep 2025 – Jan 2026): Built audit trail, snapshot diff, structured logs, and Web UI views in STIBO STEP for PDM pipelines.",
    "AI Marathon (Apr 2025 – Present): Program lead for a multi-stakeholder AI event series (7 labs, 9 events, 9 associations).",
    "SIT board (Sep 2024 – Sep 2026): Organized student initiatives and events, plus sponsorship outreach and partner coordination.",
  ],
};
