export const profile = {
  name: "Matin Khajehfard",
  location: "Hoofddorp, Netherlands",
  roles: ["Software Engineer", "Fullstack Developer", "AI and Automation Engineer"],
  valueProposition:
    "I build full stack and AI automation systems that are easy to operate: Vue and TypeScript frontends, Node or Spring APIs, SQL data models, and RAG style document search with traceable sources.",
  email: "kh.matin21@gmail.com",
  links: {
    linkedin: "https://www.linkedin.com/in/matin-khajehfard",
    github: "https://github.com/Bloody-BadAim",
  },
  preferences: ["Part time", "Hybrid", "Open to freelance", "Open to 2027 internship"],
  differentiators: [
    "Fluor: Built event driven audit trail, snapshot diff, and searchable Web UI reporting in STIBO STEP for PDM pipelines. Evidence available on request.",
    "EKB AI: Built PDF to FAISS semantic search with page level traceability and NL to EN processing. Public repo available.",
    "AI Marathon 2025-2026: Built and ran a repeatable operating model across 7 labs, 9 events, and 9 study associations.",
    "Engineering style: reliability first, structured logging, debuggability, and workflows that can be repeated by others.",
  ],
  skills: {
    frontend: ["Vue.js", "TypeScript", "JavaScript", "HTML/CSS", "Vite"],
    backend: [
      "Node.js",
      "Express",
      "NestJS",
      "Java (Spring Boot)",
      "REST APIs",
      "PostgreSQL",
      "MySQL",
      "Prisma",
      "JWT",
      "OAuth",
      "Sessions",
    ],
    ai: [
      "Python",
      "FAISS",
      "HuggingFace embeddings",
      "LangChain",
      "Chunking and overlap",
      "Metadata traceability",
      "pdfplumber",
      "pandas",
      "Argos Translate",
      "PyTorch",
    ],
    automation: ["n8n", "Power Automate", "Zapier", "Webhooks", "Validation and retries"],
    testing: ["Cypress", "Vitest", "Git", "ESLint", "Render (deployment)"],
    product: ["Figma", "UX prototyping", "Agile Scrum", "Documentation"],
    additional: ["C#", "PHP", "Unity (coursework)"],
  },
  leadership: {
    title: "AI4HvA Community Builder and AI Marathon Program Lead (CoE Applied AI)",
    details:
      "Founded and grew a student led AI community and launched the AI Marathon: a structured collaboration model between HvA AI labs and study associations. Built intake and matching, event blueprints, and execution guardrails with Responsible AI framing and evidence backed delivery.",
    metrics: ["7 labs", "9 events", "9 study associations (2025-2026)"],
    bullets: [
      "Built AI4HvA community infrastructure for visibility and ongoing engagement across channels (Teams, social, web).",
      "Designed the AI Marathon operating model: intake form, scoping workflow, event blueprints, and evaluation guardrails.",
      "Coordinated stakeholders across labs, study associations, and student boards to deliver consistent events with clear scope.",
      "Supported hackathon initiatives with sponsorship outreach and partner follow through.",
    ],
  },
  experience: [
    "Fluor (Sep 2025 - Jan 2026): Built audit trail, snapshot diff, structured logs, and Web UI views in STIBO STEP for PDM pipelines.",
    "AI Marathon (Apr 2025 - Present): Program lead for a multistakeholder AI event series (7 labs, 9 events, 9 associations).",
    "SIT board (Sep 2024 - Sep 2026): Organized student initiatives and events, plus sponsorship outreach and partner coordination.",
  ],
};
